variables:
  EC2_REGIONS:
    description: "ec2 regions"
    required: false
    type: array
    default:
     - us-east-1
  EC2_ALERTS:
    description: "Alerts array"
    required: true
    type: array
    default:
     - cc-emilkip-ec2-alert